class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      // General
      'guest_user': 'Misafir Kullanıcı',
      'unknown_business': 'Bilinmeyen İşletme',
      'cancel': 'Vazgeç',
      'send': 'Gönder',
      'error': 'Hata',
      'success_review': 'Değerlendirme kaydedildi!',
      'rate_experience': 'Deneyiminizi Oylayın',
      'rate_subtitle': 'Bize geri bildirim vererek gelişmemize yardımcı olun.',
      'submit_review': 'Gönder',
      'rated_tab': 'Değerlendirilenler',
      'pending_tab': 'Bekleyenler',
      'no_pending_reviews': 'Değerlendirilmeyi bekleyen işlem bulunmuyor.',
      'skip': 'Atla',
      'rating_comment_hint': 'Deneyiminden bahsetmek ister misin?',
      'pending_review_title': 'Ziyaretin Nasıldı?',
      'pending_review_subtitle': 'Deneyimini puanla!',
      
      // Settings
      'edit_profile': 'Profili Düzenle',
      'general': 'GENEL',
      'notifications': 'Bildirimler',
      'added_shops': 'Eklenen Kafeler',
      'order_history': 'Sipariş Geçmişi',
      'my_reviews': 'Değerlendirmelerim',
      'other': 'DİĞER',
      'privacy_security': 'Gizlilik & Güvenlik',
      'help_support': 'Yardım & Destek',
      'help_support_subtitle': 'Size nasıl yardımcı olabiliriz?',
      'whatsapp_sales_message': 'Merhabalar, Counpaign\'e kafemi eklemek için bilgi almak istiyorum.',
      'contact_support': 'Destek',
      'contact_support_desc': 'Destek talepleriniz ve ihtiyaçlarınız için bize ulaşın.',
      'contact_sales': 'Satış',
      'contact_sales_desc': 'Mekanınızı eklemek, görüşme ayarlamak, satış mümessili olmak veya satış sorularınız için bize ulaşın.',
      'contact_info': 'Bilgi',
      'contact_info_desc': 'Tavsiyelerinizi iletmek, ürün ve servislerimiz hakkında bilgi almak, ekibimize katılmak veya diğer konular için bize ulaşın.',
      'notification_settings': 'Bildirim Ayarları',
      'rate_app': 'Uygulamayı Değerlendir',
      'dark_mode': 'Karanlık Mod',
      'logout': 'Çıkış Yap',
      'language_option': 'Dil Seçeneği / Language',
      'select_language': 'Dil Seçin / Select Language',
      
      // Order History
      'no_orders_yet': 'Henüz hiç siparişiniz yok.',
      'no_orders_filter': 'Bu tarih aralığında işlem yok.',
      'stamp_earned': 'Damga Kazanıldı',
      'point_earned': 'Puan Kazanıldı',
      'gift_redeemed': 'Hediye Harcandı',
      'transaction': 'İşlem',
      'rate_transaction': 'Değerlendirme Yap',
      'rate_dialog_title': 'Harcamayı Değerlendir',
      'comment_hint': 'Yorumunuz (Opsiyonel)',
      
      // My Reviews
      'no_reviews_yet': 'Henüz hiç değerlendirme yapmadınız.',
      'no_reviews_filter': 'Bu tarih aralığında değerlendirme yok.',
      
      // Filters
      'filter_all': 'Tümü',
      'filter_today': 'Bugün',
      'filter_yesterday': 'Dün',
      'filter_1_week': '1 Hafta',
      'filter_1_month': '1 Ay',
      'filter_3_months': '3 Ay',
      'filter_1_year': '1 Sene',
      // Home
      'good_morning': 'Günaydın,',
      'good_afternoon': 'Tünaydın,',
      'good_evening': 'İyi Akşamlar,',
      'good_night': 'İyi Geceler,',
      'my_points': 'Puanlarım',
      'stamps': 'Damga',
      'explore': 'Keşfet',
      'deals': 'Diğer Kampanyalar',
      'active_campaigns': 'Aktif Kampanya',
      'explore_cafes': 'Kafeleri Keşfet',
      'venues': 'Mekan',
      'new_cafe_add': 'Yeni Kafe Ekle',
      'scan_or_enter_code': 'Kampanyalara katılmak için\nkodu okut veya gir',
      'wallet_empty': 'Cüzdan Boş',
      'scan_qr': 'QR Tara',
      'menu': 'Menü',
      'tap_to_view': 'Görüntülemek için dokun',
      'points_reward': 'Puan',
      'coffee_reward': 'Kahve',
      'stamp_reward': 'Damga',
      'all': 'Tümü',
      'in_wallet': 'Cüzdandaki Kampanyalar',
      'others': 'Yeni Kafeler',
 
      // Auth & Profile
       'login_title': 'Aramıza Yeniden\nHoşgeldin!',
       'login_subtitle': 'Kolayca Giriş Yap.',
       'register_title': 'Aramıza Katıl.',
       'register_subtitle': 'Hemen Kazanmaya Başla!',
       'name': 'Ad',
       'surname': 'Soyad',
       'phone_number': 'Telefon Numarası',
       'email': 'E-posta Adresi',
       'password': 'Şifre',
       'confirm_password': 'Şifreyi Doğrula',
       'gender': 'Cinsiyet',
       'birth_date': 'Doğum Tarihi',
       'male': 'Erkek',
       'female': 'Kadın',
       'other_gender': 'Diğer',
       'wont_share': 'Belirtmek İstemiyorum',
       'birth_date_note': '* Kayıt olduktan sonra doğum tarihini değiştiremezsiniz.',
       'forgot_password': 'Parolamı Unuttum?',
       'login_btn': 'Giriş Yap',
       'register_btn': 'Kayıt Ol',
       'no_account': 'Hesabın yok mu? Kayıt Ol',
       'already_member': 'Zaten üye misin? Giriş Yap',
       'save_changes': 'Değişiklikleri Kaydet',
       'profile_updated': 'Profil Güncellendi!',
       'changes_saved_msg': 'Değişiklikler başarıyla kaydedildi.',
       'ok': 'Tamam',
       'phone_verified_msg': 'Telefon numarası doğrulandı ve değiştirilemez.',
       'phone_not_verified_msg': 'Telefon numaranız doğrulanmamış.',
       'verify_code_title': 'Doğrulama Kodu',
       'enter_code_msg': 'Lütfen {phone} numarasına gönderilen 6 haneli kodu giriniz.',
       'verify_btn': 'DOĞRULA',
       'resend_code': 'Kodu tekrar gönder',
       'code_resent_msg': 'Kod tekrar gönderildi.',
       'code_error_msg': 'Kod gönderilemedi.',
       'verification_failed': 'Doğrulama başarısız.',
       'fill_all_fields': 'Lütfen tüm alanları doldurun.',
       'passwords_dont_match': 'Şifreler eşleşmiyor.',
       'passwords_match': 'Şifreler eşleşiyor',
       'password_updated_title': 'Şifreniz Güncellendi!',
       'password_updated_msg': 'Yeni şifreniz başarıyla kaydedildi. Artık bu şifre ile giriş yapabilirsiniz.',
       'password_security_tip': 'Güvenliğiniz için şifrenizi düzenli aralıklarla güncellemenizi öneririz.',
       'password_min_chars': 'Şifre en az 6 karakter olmalıdır',
       'field_required': 'Bu alan boş bırakılamaz',
       'update_failed': 'Güncelleme başarısız oldu.',
       'an_error_occurred': 'Bir hata oluştu.',
       'invalid_email': 'Geçersiz e-posta adresi.',
       'phone_start_5': 'Telefon numarası 5 ile başlamalıdır.',
      'search_deal_venue': 'Fırsat veya mekan ara...',
      'no_deals_found': 'Kriterlere uygun fırsat bulunamadı.',
      'no_active_deals_firm': 'aktif fırsatı yok.',

      // Notifications
      'delete_all': 'Tümünü Temizle',
      'no_notifications': 'Bildirim yok.',
      'notification_deleted': 'Bildirim silindi.',
      'notif_welcome_title': 'Hoşgeldin! 🎉',
      'notif_welcome_msg': 'Kayıt olduğun için teşekkürler.',
      'notif_coffee_title': 'Kahve Kampanyası ☕',
      'notif_coffee_msg': 'Espresso Lab\'de tüm kahvelerde %20 indirim!',
      'notif_points_title': 'Puan Kazanıldı',
      'notif_points_msg': 'Son harcamandan 150 puan kazandın.',

      // Business Detail
      'gifts': 'Hediyeler',
      'past_transactions': 'Geçmiş İşlemler',
      'scan_for_points': 'Puan için Okut',
      'gift_store': 'Hediye Mağazası',
      'your_balance': 'Bakiyen',
      'stamps_progress': 'Sadakat Kartı Durumu',
      'loading': 'Yükleniyor...',

      // Explore Cafes
      'search_cafe': 'Kafe ara...',
      'no_cafes_found': 'Kriterlere uygun kafe bulunamadı.',
      'newly_added': 'Yeni Eklenenler',
      'newly_added_subtitle': 'Bölgene yeni katılanlar',
      'discover_new_places': 'Yeni mekanları keşfet',
      'all_businesses': 'Tüm İşletmeler',
      'no_address': 'Adres bilgisi yok',
      'no_cafes_yet': 'Henüz keşfedilecek yeni mekan yok.',
      'new_badge': 'YENİ',

      // Business categories
      'cat_kafe': 'Kafe',
      'cat_restoran': 'Restoran',
      'cat_bar': 'Bar',
      'cat_fırın': 'Fırın',
      'cat_pastane': 'Pastane',
      'cat_market': 'Market',
      'cat_spor': 'Spor',
      'cat_güzellik': 'Güzellik',
      'cat_giyim': 'Giyim',
      'cat_teknoloji': 'Teknoloji',

      // Gift Selection
      'gift_selection_title': 'Hediye Seçimi',
      'spendable_amount': 'Harcanabilir Miktar',
      'gift_entitlement_title': 'Hediye Hakkınız Var!',
      'gift_entitlement_subtitle': 'adet hediyeniz birikti.',
      'no_gifts_yet': 'Henüz hediye bulunmuyor.',
      'available_gifts_header': 'Kullanılabilir Hediyeler',
      'points': 'Puan',
      'insufficient_points': 'Yetersiz Puan',

      // Campaign Detail
      'reward_label': 'Ödül',
      'date_label': 'Son Tarih',
      'discount_label': 'İNDİRİM',
      'campaign_label': 'Kampanya',
      'about_campaign': 'Kampanya Hakkında',
      'how_to_use': 'Nasıl Faydalanırım?',
      'step_1': 'İşletmede QR kodunu okut.',
      'step_2': 'Kazandığın ödülleri cüzdanında gör.',

      // Business Detail (Extra)
      'no_gift_to_spend': 'Harcayacak hediye ürününüz bulunmuyor! 🥐',
      'payment_qr': 'Ödeme QR Kodu',
      'scan_to_redeem': 'Kasiyere okutarak hediye ürününü alabilirsin.',
      'close': 'Kapat',
      'my_coffees': 'Kahvelerim',
      'spend_qr': 'Puan Harca',
      'spend_gifts': 'Hediyelerini harca',
      'campaigns': 'Kampanyalar',
      'no_campaigns_soon': 'Yakında yeni fırsatlar burada olacak! ✨',
      'add_to_wallet': 'Cüzdana Ekle',
      'added_to_wallet_msg': 'Bu işletme artık cüzdanında! 🎉',
      'locked_business_title': 'Bu İşletme Kilitli',
      'locked_business_subtitle': 'Bu işletmenin içeriğini görmek için önce cüzdanına eklemen gerekiyor.',

      // Add Firm Screen
      'page_title_add_cafe': 'Kafe Ekle',
      'dropdown_city': 'İl',
      'dropdown_district': 'İlçe',
      'dropdown_neighborhood': 'Semt',
      'section_new_cafes': 'Yeni Eklenen Kafeler',
      'section_all_cafes': 'Tüm Kafeler',
      'success_firm_added': 'İşletme eklendi!',
      
      // My Firms Screen
      'my_firms_title': 'Eklenen Kafeler',
      'swipe_hint': 'Basılı tut ve sürükle ile sırala',
      'no_firms_added': 'Henüz kafe eklemediniz',
      'no_firms_added_sub': 'Cüzdanına kafe ekle, kampanyaları takip et',
      'delete_firm_title': 'Mağazayı Sil',
      'delete_firm_content': 'Bu Mağazayı Silmeniz Durumunda Kazandığınız Puanlar Silinecektir.\n\nOnaylıyor musunuz?',
      'yes_delete': 'Evet, Sil',
      'security_verification': 'Güvenlik Doğrulaması',
      'enter_password_msg': 'İşlemi tamamlamak için lütfen şifrenizi giriniz.',
      'your_password': 'Şifreniz',
      'confirm': 'Onayla',
      'firm_deleted_success': 'Mağaza başarıyla silindi.',
      'error_reorder': 'Sıralama kaydedilemedi',

      'info': 'Bilgi',
      'success_title': 'Başarılı',
      
      // Scanner Screen
      'scan_qr_title': 'QR TARA',
      'camera_error': 'Kamera Hatası',
      'waiting_approval': 'İşletme Onayı Bekleniyor...',
      'waiting_approval_msg': 'Lütfen kasiyerin işlemi onaylamasını bekleyin.',
      'approved': 'İşlem Onaylandı! 🎉',
      'tab_history': 'Geçmiş',
      'tab_pending': 'Bekleyenler',
      'rate_now': 'Değerlendir',
      'timeout_msg': 'Zaman aşımı. Lütfen tekrar deneyin veya kasiyere danışın.',
      'scan_error_title': 'QR Okuma Hatası',
      'firm_mismatch_error': 'Hatalı İşletme!\nBeklenen: ',
      'expired_qr_error': 'Bu QR kodun süresi dolmuş veya geçersiz.',
      'invalid_qr_error': 'Hatalı QR kodu.',
      'session_error': 'Oturum hatası. Lütfen tekrar giriş yapın.',
      'earn_points_msg': 'QR kodu tarayarak puan kazanın',
      'total_points': 'Toplam Puan',
      'gift': 'Hediye',
      'confirm_redeem_title': 'Puan Harca',
      'confirm_redeem_msg': 'Ürününü almak istediğinize emin misiniz?\n',
      'gift_code_title': 'Hediye Kodu',
      'gift_code_desc': 'Bu kodu kasa personeline göstererek\nhediyenizi teslim alabilirsiniz.',
      'gift_delivered_msg': 'Hediye teslim edildi! 🎉',
      'redeem_entitlement_title': 'Hediye Hakkı Kullan',
      'gift_entitlement_confirm': '1 adet hediye hakkınızı kullanmak istiyor musunuz?',
      'gift_error_msg': 'Hediye hakkı kullanılırken hata oluştu.',

      // Campaign Detail Dynamic
      'joined_status': 'Katıldın ✅',
      'join_now_btn': 'Hemen Katıl',
      'add_firm_first_btn': 'Önce İşletmeyi Ekle',
      'need_add_firm_msg': 'Bu kampanyaya katılmak için önce işletmeyi cüzdanına eklemelisin! 🛍️',
      
      // Auto-Translation Keys
      'kod_iptal_edildi': 'İşletme tarafından iptal edildi', 
      'hediye_alimi': 'Hediye Alımı',
      'hediye_hakki_kullanimi': 'Hediye Hakkı Kullanımı',

      // Section Headers
      'menu_header': 'Menü',
      'active_campaigns_header': 'Aktif Kampanyalar',
      'view_all': 'Tümünü gör',
      'menu_preparing': 'Menü Hazırlanıyor...',
      'view_details': 'Detayları Gör',
      'product_description_title': 'Ürün Açıklaması',
      'no_product_description': 'Bu ürün için henüz açıklama eklenmemiş.',
      'price_label': 'Fiyat',
      'final_price_label': 'Ödenecek Tutar',

      // Sort
      'sort_title': 'Sıralama',
      'sort_default': 'Varsayılan',
      'sort_price_asc': 'Fiyat: Artan',
      'sort_price_desc': 'Fiyat: Azalan',

      // Menu Categories
      'cat_all': 'Tümü',
      'cat_deals': 'Fırsatlar',
      'cat_hot_coffee': 'Sıcak Kahveler',
      'cat_cold_coffee': 'Soğuk Kahveler',
      'cat_hot_drinks': 'Sıcak İçecekler',
      'cat_cold_drinks': 'Soğuk İçecekler',
      'cat_desserts': 'Tatlılar',

      // Business Detail — category display
      'popular_section': 'Popüler',

      // Gift / Spend Points screen
      'points_in_account': 'Kullanılabilir puan',
      'points_expire_note': 'Puanlar, kazanıldıktan 6 ay\nsonra kaybolur',
      'points_menu_title': 'Puan Menüsü',
      'gift_all_cat': 'Tümü',

      // Order History unit labels
      'unit_stamp': 'Damga',
      'unit_point': 'Puan',
      'unit_gift': 'Hediye',
      'point_spending': 'Puan Harcama',



      // UI & Popups
      'qr_okut': 'QR Okut',
      'puan_harca': 'Puan Harca',
      'siparislerim': 'Siparişlerim',
      'hediye_icecek': 'Hediye İçecek',
      'stamp_label': 'Damga',
      'point_label': 'Puan',
      'reviews_count': 'değerlendirme',
      'account_deleted_msg': 'Hesabınız başarıyla silindi.',
      'delete_failed_msg': 'Silme işlemi başarısız.',
      'action_failed': 'İşlem başarısız',
      'no_products_in_cat': 'Bu kategoride ürün bulunamadı.',
      'review_saved_toast': 'Değerlendirmeniz başarıyla\nkaydedildi.',
      'no_campaigns_popup': 'Bu işletmede aktif kampanya bulunamadı.',
      'password_required': 'Şifre girmelisiniz.',
      'no_active_campaigns_title': 'Aktif Kampanya Bulunamadı',
      'no_active_campaigns_desc': '{firmName} işletmesinin henüz aktif bir kampanyası bulunmamaktadır.',
      'thank_you': 'Teşekkürler!',
      'rating': 'Değerlendirme',
      'optional_note_hint': 'İsteğe bağlı bir not ekleyin...',
      'save': 'Kaydet',
      'let_pick_1': 'İlk kahveni\n',
      'let_pick_2': 'birlikte\n',
      'let_pick_3': 'seçelim!',
      'no_pending_1': 'Değerlendirilecek',
      'no_pending_2': 'ziyaretiniz bulunmuyor.',
      'see_you_again': 'Yine bekleriz!',
      'how_was_visit': 'Ziyaretin nasıldı?',
      'rate_experience_title': 'Deneyimini puanla!',
      'discover': 'Keşfet',
      'in_your_area': 'Bölgendeki\n',
      'delete_account_title': 'Hesabı Sil',
      'delete_account_desc': 'Hesabınızı silmek geri alınamaz bir işlemdir. Tüm puanlarınız, hediye geçmişiniz ve kişisel verileriniz kalıcı olarak silinecektir.\n\nİşlemi onaylamak için lütfen mevcut şifrenizi giriniz:',
      'change_password': 'Şifre Değiştir',
      'privacy_policy': 'Gizlilik & Güvenlik',
      'user_agreement': 'Kullanıcı Sözleşmesi',
      'kvkk_title': 'KVKK Aydınlatma Metni',
      'review_rules_title': 'Değerlendirme Kuralları',
      'accept_agreement_text': 'Counpaign Üyelik Sözleşmesi\'ni okudum ve kabul ediyorum.',
      'accept_kvkk_text': 'Kişisel Verilerin İşlenmesine İlişkin Aydınlatma Metni\'ni okudum.',
      'accept_agreements_msg': 'Devam etmek için sözleşmeleri kabul etmeniz gerekmektedir.',
      'popular_products': 'Öne Çıkanlar',
      'confirm_delete_btn': 'SİL',
      'cancel_btn': 'İPTAL',
      'crop_image': 'Fotoğrafı Kırp',
      'done': 'Bitti',
      'current_password': 'Mevcut Şifre',
      'new_password': 'Yeni Şifre',
      'update': 'GÜNCELLE',

      // Forgot Password Screen
      'forgot_password_title': 'Şifremi Unuttum',
      'verification_title': 'Doğrulama',
      'new_password_title': 'Yeni Şifre',
      'phone_number_label': 'Telefon Numaranız',
      'phone_number_desc': 'Hesabınıza kayıtlı telefon numaranızı girin. Size doğrulama kodu göndereceğiz.',
      'enter_code_title': 'Kodu Girin',
      'otp_desc_prefix': 'numarasına gönderilen 6 haneli kodu girin.',
      'new_password_desc': 'Lütfen yeni şifrenizi belirleyin.',
      'new_password_hint': 'Yeni Şifre',
      'confirm_password_hint': 'Şifreyi Onayla',
      'send_code_btn': 'KOD GÖNDER',
      'update_password_btn': 'ŞİFREYİ GÜNCELLE',
      'go_back_btn': 'Geri Dön',
      'invalid_phone_msg': 'Lütfen geçerli bir telefon numarası girin.',
      'code_sent_msg': 'Doğrulama kodu gönderildi.',
      'sms_failed_msg': 'SMS gönderilemedi. Numaranızı kontrol edin.',
      'enter_6_digit_msg': 'Lütfen 6 haneli kodu girin.',
      'code_verified_msg': 'Kod doğrulandı. Yeni şifrenizi belirleyin.',
      'invalid_code_msg': 'Geçersiz doğrulama kodu.',
      'password_min_6_msg': 'Şifreniz en az 6 karakter olmalıdır.',
      'passwords_no_match_msg': 'Şifreler uyuşmuyor.',
      'password_reset_success': 'Şifreniz başarıyla güncellendi.',
      'password_same_error': 'Yeni şifreniz eski şifrenizle aynı olamaz. Lütfen farklı bir şifre belirleyin.',

      // Verification Screen
      'verification_code_title': 'Doğrulama Kodu',
      'verification_code_desc_prefix': 'Lütfen',
      'verification_code_desc_suffix': 'numarasına gönderilen 6 haneli kodu giriniz.',
      'verify_action': 'DOĞRULA',

      // Login/Register Errors
      'fill_all_fields_msg': 'Lütfen tüm alanları doldurun.',
      'phone_start_5_msg': 'Telefon numarası 5 ile başlamalıdır.',
      'invalid_email_msg': 'Lütfen geçerli bir e-posta adresi giriniz.',
      'passwords_dont_match_msg': 'Şifreler eşleşmiyor.',
      'email_in_use': 'Bu e-posta adresi zaten kullanımda.',
      'invalid_email_firebase': 'Geçersiz e-posta adresi.',
      'weak_password': 'Şifreniz çok zayıf.',
      'user_not_found': 'Kullanıcı bulunamadı.',
      'wrong_password': 'Şifre hatalı.',
      'invalid_credential': 'Şifre veya kullanıcı bilgisi hatalı.',
      'user_disabled': 'Bu hesap devre dışı bırakılmış.',
      'login_error_prefix': 'Giriş Hatası',
      'server_error_prefix': 'Sunucu Hatası',
      'register_failed': 'Kayıt Başarısız. Bilgilerinizi kontrol ediniz.',
    },

    'en': {
      // Campaign Detail (EN)
      'reward_label': 'Reward',
      'date_label': 'End Date',
      'discount_label': 'DISCOUNT',
      'campaign_label': 'Campaign',
      'about_campaign': 'About Campaign',
      'how_to_use': 'How to Use?',
      'step_1': 'Scan the QR code at the business.',
      'step_2': 'See your rewards instantly in your wallet.',
      
      // Business Detail (Extra - EN)
      'no_gift_to_spend': 'You have no gifts to spend! 🥐',
      'payment_qr': 'Payment QR Code',
      'scan_to_redeem': 'Scan at the cashier to redeem your gift.',
      'close': 'Close',
      'my_coffees': 'My Coffees',
      'spend_qr': 'Spend QR',
      'spend_gifts': 'Spend your gifts',
      'campaigns': 'Campaigns',
      'no_campaigns_soon': 'New deals will be here soon! ✨',
      'add_to_wallet': 'Add to Wallet',
      'added_to_wallet_msg': 'Business added to your wallet! 🎉',
      'locked_business_title': 'This Business is Locked',
      'locked_business_subtitle': 'Add this business to your wallet to see its content.',
      
      // Add Firm Screen (EN)
      'page_title_add_cafe': 'Add Cafe',
      'dropdown_city': 'City',
      'dropdown_district': 'District',
      'dropdown_neighborhood': 'Neighborhood',
      'section_new_cafes': 'New Cafes',
      'section_all_cafes': 'All Cafes',
      'success_firm_added': 'Business added!',
      
      // My Firms Screen (EN)
      'my_firms_title': 'Added Cafes',
      'swipe_hint': 'Hold and drag to reorder',
      'no_firms_added': 'No cafes added yet',
      'no_firms_added_sub': 'Add a cafe to your wallet and track its deals',
      'delete_firm_title': 'Delete Shop',
      'delete_firm_content': 'Deleting this shop will also delete your earned points.\n\nAre you sure?',
      'yes_delete': 'Yes, Delete',
      'security_verification': 'Security Verification',
      'enter_password_msg': 'Please enter your password to complete this action.',
      'your_password': 'Your Password',
      'confirm': 'Confirm',
      'firm_deleted_success': 'Shop deleted successfully.',
      'error_reorder': 'Could not save order',

      // Popups (EN)
      'success_title': 'Success',
      'info': 'Info',
      
      // Scanner Screen (EN)
      'scan_qr_title': 'SCAN QR',
      'camera_error': 'Camera Error',
      'waiting_approval': 'Waiting for Approval...',
      'waiting_approval_msg': 'Please wait for the cashier to approve.',
      'approved': 'Transaction Approved! 🎉',
      'tab_history': 'History',
      'tab_pending': 'Pending',
      'rate_now': 'Rate Now',
      'timeout_msg': 'Timeout. Please try again or ask the cashier.',
      'scan_error_title': 'QR Scan Error',
      'firm_mismatch_error': 'Wrong Business!\nExpected: ',
      'expired_qr_error': 'QR code expired or invalid.',
      'invalid_qr_error': 'Invalid QR code.',
      'session_error': 'Session error. Please login again.',
      'earn_points_msg': 'Scan QR to earn points',
      'total_points': 'Total Points',
      'gift': 'Gift',

      // General
      'guest_user': 'Guest User',
      'unknown_business': 'Unknown Business',
      'cancel': 'Cancel',
      'send': 'Submit',
      'error': 'Error',
      'success_review': 'Review saved!',
      'rate_experience': 'Rate Your Experience',
      'rate_subtitle': 'Help us improve by providing feedback.',
      'submit_review': 'Submit Review',
      'rated_tab': 'Rated',
      'pending_tab': 'Pending',
      'no_pending_reviews': 'No pending reviews found.',
      'skip': 'Skip',
      'rating_comment_hint': 'Want to tell us about your experience?',
      'pending_review_title': 'How was your visit?',
      'pending_review_subtitle': 'Rate your experience!',
 
      // Settings
      'edit_profile': 'Edit Profile',
      'general': 'GENERAL',
      'notifications': 'Notifications',
      'added_shops': 'Added Cafes',
      'order_history': 'Order History',
      'my_reviews': 'My Reviews',
      'other': 'OTHER',
      'privacy_security': 'Privacy & Security',
      'help_support': 'Help & Support',
      'help_support_subtitle': 'How can we help you?',
      'whatsapp_sales_message': 'Hello, I would like to get information about adding my cafe to Counpaign.',
      'contact_support': 'Support',
      'contact_support_desc': 'Contact us for your support requests and needs.',
      'contact_sales': 'Sales',
      'contact_sales_desc': 'To add your venue, schedule a meeting, become a sales representative, or ask sales-related questions.',
      'contact_info': 'Info',
      'contact_info_desc': 'Share your feedback, learn about our products and services, join our team, or reach us for anything else.',
      'notification_settings': 'Notification Settings',
      'rate_app': 'Rate App',
      'dark_mode': 'Dark Mode',
      'logout': 'Logout',
      'language_option': 'Language / Dil Seçeneği',
      'select_language': 'Select Language / Dil Seçin',
 
      // Order History
      'no_orders_yet': 'No orders yet.',
      'no_orders_filter': 'No transactions in this period.',
      'stamp_earned': 'Stamp Earned',
      'point_earned': 'Point Earned',
      'gift_redeemed': 'Gift Redeemed',
      'transaction': 'Transaction',
      'rate_transaction': 'Rate',
      'rate_dialog_title': 'Rate Transaction',
      'comment_hint': 'Your Comment (Optional)',
 
      // My Reviews
      'no_reviews_yet': 'No reviews yet.',
      'no_reviews_filter': 'No reviews in this period.',
 
      // Filters
      'filter_all': 'All',
      'filter_today': 'Today',
      'filter_yesterday': 'Yesterday',
      'filter_1_week': '1 Week',
      'filter_1_month': '1 Month',
      'filter_3_months': '3 Months',
      'filter_1_year': '1 Year',
      
      // Home
      'good_morning': 'Good Morning,',
      'good_afternoon': 'Good Afternoon,',
      'good_evening': 'Good Evening,',
      'good_night': 'Good Night,',
      'my_points': 'My Points',
      'stamps': 'Stamps',
      'explore': 'Explore',
      'deals': 'Other Campaigns',
      'active_campaigns': 'Active Campaigns',
      'explore_cafes': 'Explore Cafes',
      'venues': 'Venues',
      'new_cafe_add': 'Add New Cafe',
      'scan_or_enter_code': 'Scan or enter code\nto join campaigns',
      'wallet_empty': 'Wallet Empty',
      'scan_qr': 'Scan QR',
      'menu': 'Menu',
      'tap_to_view': 'Tap to view',
 
      // Auth & Profile
      'login_title': 'Welcome\nBack!',
      'login_subtitle': 'Sign In Easily.',
      'register_title': 'Join Us.',
      'register_subtitle': 'Start Earning Now!',
      'name': 'Name',
      'surname': 'Surname',
      'phone_number': 'Phone Number',
      'email': 'Email Address',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'gender': 'Gender',
      'birth_date': 'Birth Date',
      'male': 'Male',
      'female': 'Female',
      'other_gender': 'Other',
      'wont_share': 'Prefer not to say',
      'birth_date_note': '* You cannot change your birth date after registration.',
      'forgot_password': 'Forgot Password?',
      'login_btn': 'Login',
      'register_btn': 'Register',
      'no_account': 'Don\'t have an account? Register',
      'already_member': 'Already a member? Login',
      'save_changes': 'Save Changes',
      'profile_updated': 'Profile Updated!',
      'changes_saved_msg': 'Changes saved successfully.',
      'ok': 'OK',
      'phone_verified_msg': 'Phone number verified and cannot be changed.',
      'phone_not_verified_msg': 'Phone number not verified.',
      'verify_code_title': 'Verification Code',
      'enter_code_msg': 'Please enter the 6-digit code sent to {phone}.',
      'verify_btn': 'VERIFY',
      'resend_code': 'Resend code',
      'code_resent_msg': 'Code resent.',
      'code_error_msg': 'Code could not be sent.',
      'verification_failed': 'Verification failed.',
      'fill_all_fields': 'Please fill all fields.',
      'passwords_dont_match': 'Passwords do not match.',
      'passwords_match': 'Passwords match',
      'password_updated_title': 'Password Updated!',
      'password_updated_msg': 'Your new password has been saved successfully. You can now log in with your new password.',
      'password_security_tip': 'We recommend updating your password regularly for your security.',
      'password_min_chars': 'Password must be at least 6 characters',
      'field_required': 'This field is required',
      'update_failed': 'Update failed.',
      'an_error_occurred': 'An error occurred.',
      'invalid_email': 'Invalid email address.',
      'phone_start_5': 'Phone number must start with 5.',

      // Campaigns
      'all': 'All',
      'in_wallet': 'In Wallet\'s Campaigns',
      'others': 'New Cafes',
      'search_deal_venue': 'Search deals or venues...',
      'no_deals_found': 'No deals found matching your criteria.',
      'no_active_deals_firm': 'has no active deals.',
      'points_reward': 'Points',
      'coffee_reward': 'Coffee',
      'stamp_reward': 'Stamp',
 
      // Notifications
      'delete_all': 'Clear All',
      'no_notifications': 'No notifications.',
      'notification_deleted': 'Notification deleted.',
      'notif_welcome_title': 'Welcome! 🎉',
      'notif_welcome_msg': 'Thanks for signing up.',
      'notif_coffee_title': 'Coffee Camapign ☕',
      'notif_coffee_msg': '20% discount on all coffees at Espresso Lab!',
      'notif_points_title': 'Points Updated',
      'notif_points_msg': 'You earned 150 points from your last purchase.',
 
      // Business Detail
      'gifts': 'Gifts',
      'past_transactions': 'Past Transactions',
      'scan_for_points': 'Scan for Points',
      'gift_store': 'Gift Store',
      'your_balance': 'Your Balance',
      'stamps_progress': 'Loyalty Card Progress',
      'loading': 'Loading...',
 
      // Explore Cafes
      'search_cafe': 'Search cafes...',
      'no_cafes_found': 'No cafes found matching criteria.',
      'newly_added': 'Newly Added',
      'newly_added_subtitle': 'New arrivals in your area',
      'discover_new_places': 'Discover new places',
      'all_businesses': 'All Businesses',
      'no_address': 'No address info',
      'no_cafes_yet': 'No new places to explore yet.',
      'new_badge': 'NEW',

      // Business categories
      'cat_kafe': 'Cafe',
      'cat_restoran': 'Restaurant',
      'cat_bar': 'Bar',
      'cat_fırın': 'Bakery',
      'cat_pastane': 'Patisserie',
      'cat_market': 'Market',
      'cat_spor': 'Sports',
      'cat_güzellik': 'Beauty',
      'cat_giyim': 'Fashion',
      'cat_teknoloji': 'Technology',

      // Gift Selection
      'gift_selection_title': 'Gift Selection',
      'spendable_amount': 'Spendable Amount',
      'gift_entitlement_title': 'You have a Gift!',
      'gift_entitlement_subtitle': 'gifts available.',
      'no_gifts_yet': 'No gifts available yet.',
      'available_gifts_header': 'Available Gifts',
      'points': 'Points',
      'insufficient_points': 'Insufficient Points',
      'confirm_redeem_title': 'Spend Points',
      'confirm_redeem_msg': 'Are you sure you want to redeem ',
      'gift_code_title': 'Gift Code',
      'gift_code_desc': 'Show this code to cashier to receive your gift.',
      'gift_delivered_msg': 'Gift delivered! 🎉',
      'redeem_entitlement_title': 'Use Free Gift',
      'gift_entitlement_confirm': 'Do you want to use 1 free gift entitlement?',
      'gift_error_msg': 'Error processing gift.',
      
      // Campaign Detail Dynamic
      'joined_status': 'Joined ✅',
      'join_now_btn': 'Join Now',
      'add_firm_first_btn': 'Add Shop First',
      'need_add_firm_msg': 'You must add this shop to your wallet first! 🛍️',
      
      // Auto-Translation Keys (Backend Mappings)
      'kod_iptal_edildi': 'Cancelled by business', 
      'hediye_alimi': 'Gift Redemption', 
      'hediye_hakki_kullanimi': 'Free Gift Entitlement Used', 

      // Section Headers
      'menu_header': 'Menu',
      'active_campaigns_header': 'Active Campaigns',
      'view_all': 'View all',
      'menu_preparing': 'Menu is Being Prepared...',
      'view_details': 'View Details',
      'product_description_title': 'Product Description',
      'no_product_description': 'No description available for this product.',
      'price_label': 'Price',
      'final_price_label': 'Total',

      // Sort
      'sort_title': 'Sort',
      'sort_default': 'Default',
      'sort_price_asc': 'Price: Low to High',
      'sort_price_desc': 'Price: High to Low',

      // Menu Categories
      'cat_all': 'All',
      'cat_deals': 'Deals',
      'cat_hot_coffee': 'Hot Coffees',
      'cat_cold_coffee': 'Cold Coffees',
      'cat_hot_drinks': 'Hot Drinks',
      'cat_cold_drinks': 'Cold Drinks',
      'cat_desserts': 'Desserts',

      // Business Detail — category display
      'popular_section': 'Popular',

      // Gift / Spend Points screen
      'points_in_account': 'Available points',
      'points_expire_note': 'Points expire after 6 months.',
      'points_menu_title': 'Points Menu',
      'gift_all_cat': 'All',

      // Order History unit labels
      'unit_stamp': 'Stamp',
      'unit_point': 'Points',
      'unit_gift': 'Gift',
      'point_spending': 'Points Spent',


      // UI & Popups
      'qr_okut': 'Scan QR',
      'puan_harca': 'Spend Points',
      'siparislerim': 'My Orders',
      'hediye_icecek': 'Free Drink',
      'stamp_label': 'Stamp',
      'point_label': 'Points',
      'reviews_count': 'reviews',
      'account_deleted_msg': 'Your account has been deleted.',
      'delete_failed_msg': 'Delete operation failed.',
      'action_failed': 'Action failed',
      'no_products_in_cat': 'No products in this category.',
      'review_saved_toast': 'Your review has been saved.',
      'no_campaigns_popup': 'No active campaigns found for this business.',
      'password_required': 'Password is required.',
      'no_active_campaigns_title': 'No Active Campaigns Found',
      'no_active_campaigns_desc': '{firmName} does not have any active campaigns yet.',
      'thank_you': 'Thank You!',
      'rating': 'Rating',
      'optional_note_hint': 'Add an optional note...',
      'save': 'Save',
      'let_pick_1': "Let's pick\n",
      'let_pick_2': 'your first\n',
      'let_pick_3': 'coffee!',
      'no_pending_1': 'No pending',
      'no_pending_2': 'visits to review.',
      'see_you_again': 'See you again!',
      'how_was_visit': 'How was your visit?',
      'rate_experience_title': 'Rate your experience!',
      'discover': 'Discover',
      'in_your_area': 'Local\n',
      'delete_account_title': 'Delete Account',
      'delete_account_desc': 'Deleting your account is permanent. All your points, gift history, and personal data will be permanently removed.\n\nPlease enter your current password to confirm:',
      'change_password': 'Change Password',
      'privacy_policy': 'Privacy & Security',
      'user_agreement': 'User Agreement',
      'kvkk_title': 'Data Protection Notice',
      'review_rules_title': 'Review Rules',
      'accept_agreement_text': 'I have read and accept the Counpaign Membership Agreement.',
      'accept_kvkk_text': 'I have read the Personal Data Processing Notice.',
      'accept_agreements_msg': 'You must accept the agreements to continue.',
      'popular_products': 'Featured Products',
      'confirm_delete_btn': 'DELETE',
      'cancel_btn': 'CANCEL',
      'crop_image': 'Crop Image',
      'done': 'Done',
      'phone_length_error': 'Must be 10 digits (without leading 0)',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'update': 'UPDATE',

      // Forgot Password Screen
      'forgot_password_title': 'Forgot Password',
      'verification_title': 'Verification',
      'new_password_title': 'New Password',
      'phone_number_label': 'Your Phone Number',
      'phone_number_desc': 'Enter the phone number linked to your account. We will send you a verification code.',
      'enter_code_title': 'Enter Code',
      'otp_desc_prefix': 'Enter the 6-digit code sent to',
      'new_password_desc': 'Please set your new password.',
      'new_password_hint': 'New Password',
      'confirm_password_hint': 'Confirm Password',
      'send_code_btn': 'SEND CODE',
      'update_password_btn': 'UPDATE PASSWORD',
      'go_back_btn': 'Go Back',
      'invalid_phone_msg': 'Please enter a valid phone number.',
      'code_sent_msg': 'Verification code sent.',
      'sms_failed_msg': 'Failed to send SMS. Please check your number.',
      'enter_6_digit_msg': 'Please enter the 6-digit code.',
      'code_verified_msg': 'Code verified. Set your new password.',
      'invalid_code_msg': 'Invalid verification code.',
      'password_min_6_msg': 'Password must be at least 6 characters.',
      'passwords_no_match_msg': 'Passwords do not match.',
      'password_reset_success': 'Your password has been updated successfully.',
      'password_same_error': 'Your new password cannot be the same as your old one. Please choose a different password.',

      // Verification Screen
      'verification_code_title': 'Verification Code',
      'verification_code_desc_prefix': 'Please enter the 6-digit code sent to',
      'verification_code_desc_suffix': '',
      'verify_action': 'VERIFY',

      // Login/Register Errors
      'fill_all_fields_msg': 'Please fill in all fields.',
      'phone_start_5_msg': 'Phone number must start with 5.',
      'invalid_email_msg': 'Please enter a valid email address.',
      'passwords_dont_match_msg': 'Passwords do not match.',
      'email_in_use': 'This email is already in use.',
      'invalid_email_firebase': 'Invalid email address.',
      'weak_password': 'Your password is too weak.',
      'user_not_found': 'User not found.',
      'wrong_password': 'Incorrect password.',
      'invalid_credential': 'Invalid password or user credentials.',
      'user_disabled': 'This account has been disabled.',
      'login_error_prefix': 'Login Error',
      'server_error_prefix': 'Server Error',
      'register_failed': 'Registration failed. Please check your information.',
    },
  };

  static String getString(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}
