class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'tr': {
      // General
      'guest_user': 'Misafir Kullanıcı',
      'unknown_business': 'Bilinmeyen İşletme',
      'cancel': 'Vazgeç',
      'send': 'Gönder',
      'error': 'Hata',
      'success_review': 'Değerlendirme kaydedildi!',
      
      // Settings
      'edit_profile': 'Profili Düzenle',
      'general': 'GENEL',
      'notifications': 'Bildirimler',
      'added_shops': 'Eklenen Dükkanlar',
      'order_history': 'Sipariş Geçmişi',
      'my_reviews': 'Değerlendirmelerim',
      'other': 'DİĞER',
      'privacy_security': 'Gizlilik & Güvenlik',
      'help_support': 'Yardım & Destek',
      'notification_settings': 'Bildirim Ayarları',
      'rate_app': 'Uygulamayı Değerlendir',
      'dark_mode': 'Karanlık Mod',
      'logout': 'Çıkış Yap',
      'language_option': 'Dil Seçeneği / Language',
      'select_language': 'Dil Seçin / Select Language',
      
      // Order History
      'no_orders_yet': 'Henüz hiç siparişiniz yok.',
      'no_orders_filter': 'Bu tarih aralığında işlem yok.',
      'stamp_earned': 'Damga Kazanıldı',
      'point_earned': 'Puan Kazanıldı',
      'gift_redeemed': 'Hediye Harcandı',
      'transaction': 'İşlem',
      'rate_transaction': 'Değerlendirme Yap',
      'rate_dialog_title': 'Harcamayı Değerlendir',
      'comment_hint': 'Yorumunuz (Opsiyonel)',
      
      // My Reviews
      'no_reviews_yet': 'Henüz hiç değerlendirme yapmadınız.',
      'no_reviews_filter': 'Bu tarih aralığında değerlendirme yok.',
      
      // Filters
      'filter_all': 'Tümü',
      'filter_today': 'Bugün',
      'filter_yesterday': 'Dün',
      'filter_1_week': '1 Hafta',
      'filter_1_month': '1 Ay',
      'filter_3_months': '3 Ay',
      'filter_1_year': '1 Sene',
      // Home
      'good_morning': 'Günaydın,',
      'good_afternoon': 'Tünaydın,',
      'good_evening': 'İyi Akşamlar,',
      'good_night': 'İyi Geceler,',
      'my_points': 'Puanlarım',
      'stamps': 'Damga',
      'explore': 'Keşfet',
      'deals': 'Fırsatlar',
      'active_campaigns': 'Aktif Kampanya',
      'explore_cafes': 'Kafeleri Keşfet',
      'venues': 'Mekan',
      'new_cafe_add': 'Yeni Kafe Ekle',
      'scan_or_enter_code': 'Kampanyalara katılmak için\nkodu okut veya gir',
      'wallet_empty': 'Cüzdan Boş',
      'scan_qr': 'QR Tara',
 
      // Auth & Profile
       'login_title': 'Hoşgeldin.\nGiriş Yap.',
       'register_title': 'Hesap\nOluştur.',
       'name': 'Ad',
       'surname': 'Soyad',
       'phone_number': 'Telefon Numarası',
       'email': 'E-posta Adresi',
       'password': 'Şifre',
       'confirm_password': 'Şifreyi Doğrula',
       'gender': 'Cinsiyet',
       'birth_date': 'Doğum Tarihi',
       'male': 'Erkek',
       'female': 'Kadın',
       'other_gender': 'Diğer',
       'wont_share': 'Belirtmek İstemiyorum',
       'forgot_password': 'Parolamı Unuttum?',
       'login_btn': 'Giriş Yap',
       'register_btn': 'Kayıt Ol',
       'no_account': 'Hesabın yok mu? Kayıt Ol',
       'already_member': 'Zaten üye misin? Giriş Yap',
       'save_changes': 'Değişiklikleri Kaydet',
       'profile_updated': 'Profil Güncellendi!',
       'changes_saved_msg': 'Değişiklikler başarıyla kaydedildi.',
       'ok': 'Tamam',
       'phone_verified_msg': 'Telefon numarası doğrulandı ve değiştirilemez.',
       'phone_not_verified_msg': 'Telefon numaranız doğrulanmamış.',
       'verify_code_title': 'Doğrulama Kodu',
       'enter_code_msg': 'Lütfen {phone} numarasına gönderilen 6 haneli kodu giriniz.',
       'verify_btn': 'DOĞRULA',
       'resend_code': 'Kodu tekrar gönder',
       'code_resent_msg': 'Kod tekrar gönderildi.',
       'code_error_msg': 'Kod gönderilemedi.',
       'verification_failed': 'Doğrulama başarısız.',
       'fill_all_fields': 'Lütfen tüm alanları doldurun.',
       'passwords_dont_match': 'Şifreler eşleşmiyor.',
       'invalid_email': 'Geçersiz e-posta adresi.',
       'phone_start_5': 'Telefon numarası 5 ile başlamalıdır.',
    },
    'en': {
      // General
      'guest_user': 'Guest User',
      'unknown_business': 'Unknown Business',
      'cancel': 'Cancel',
      'send': 'Submit',
      'error': 'Error',
      'success_review': 'Review saved!',
 
      // Settings
      'edit_profile': 'Edit Profile',
      'general': 'GENERAL',
      'notifications': 'Notifications',
      'added_shops': 'My Firms',
      'order_history': 'Order History',
      'my_reviews': 'My Reviews',
      'other': 'OTHER',
      'privacy_security': 'Privacy & Security',
      'help_support': 'Help & Support',
      'notification_settings': 'Notification Settings',
      'rate_app': 'Rate App',
      'dark_mode': 'Dark Mode',
      'logout': 'Logout',
      'language_option': 'Language / Dil Seçeneği',
      'select_language': 'Select Language / Dil Seçin',
 
      // Order History
      'no_orders_yet': 'No orders yet.',
      'no_orders_filter': 'No transactions in this period.',
      'stamp_earned': 'Stamp Earned',
      'point_earned': 'Point Earned',
      'gift_redeemed': 'Gift Redeemed',
      'transaction': 'Transaction',
      'rate_transaction': 'Rate',
      'rate_dialog_title': 'Rate Transaction',
      'comment_hint': 'Your Comment (Optional)',
 
      // My Reviews
      'no_reviews_yet': 'No reviews yet.',
      'no_reviews_filter': 'No reviews in this period.',
 
      // Filters
      'filter_all': 'All',
      'filter_today': 'Today',
      'filter_yesterday': 'Yesterday',
      'filter_1_week': '1 Week',
      'filter_1_month': '1 Month',
      'filter_3_months': '3 Months',
      'filter_1_year': '1 Year',
      
      // Home
      'good_morning': 'Good Morning,',
      'good_afternoon': 'Good Afternoon,',
      'good_evening': 'Good Evening,',
      'good_night': 'Good Night,',
      'my_points': 'My Points',
      'stamps': 'Stamps',
      'explore': 'Explore',
      'deals': 'Deals',
      'active_campaigns': 'Active Campaigns',
      'explore_cafes': 'Explore Cafes',
      'venues': 'Venues',
      'new_cafe_add': 'Add New Cafe',
      'scan_or_enter_code': 'Scan or enter code\nto join campaigns',
      'wallet_empty': 'Wallet Empty',
      'scan_qr': 'Scan QR',
 
      // Auth & Profile
      'login_title': 'Welcome.\nLogin.',
      'register_title': 'Create\nAccount.',
      'name': 'Name',
      'surname': 'Surname',
      'phone_number': 'Phone Number',
      'email': 'Email Address',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'gender': 'Gender',
      'birth_date': 'Birth Date',
      'male': 'Male',
      'female': 'Female',
      'other_gender': 'Other',
      'wont_share': 'Prefer not to say',
      'forgot_password': 'Forgot Password?',
      'login_btn': 'Login',
      'register_btn': 'Register',
      'no_account': 'Don\'t have an account? Register',
      'already_member': 'Already a member? Login',
      'save_changes': 'Save Changes',
      'profile_updated': 'Profile Updated!',
      'changes_saved_msg': 'Changes saved successfully.',
      'ok': 'OK',
      'phone_verified_msg': 'Phone number verified and cannot be changed.',
      'phone_not_verified_msg': 'Phone number not verified.',
      'verify_code_title': 'Verification Code',
      'enter_code_msg': 'Please enter the 6-digit code sent to {phone}.',
      'verify_btn': 'VERIFY',
      'resend_code': 'Resend code',
      'code_resent_msg': 'Code resent.',
      'code_error_msg': 'Code could not be sent.',
      'verification_failed': 'Verification failed.',
      'fill_all_fields': 'Please fill all fields.',
      'passwords_dont_match': 'Passwords do not match.',
      'invalid_email': 'Invalid email address.',
      'phone_start_5': 'Phone number must start with 5.',

      // Campaigns
      'all': 'All',
      'in_wallet': 'In Wallet',
      'others': 'Others',
      'search_deal_venue': 'Search deals or venues...',
      'no_deals_found': 'No deals found matching your criteria.',
      'no_active_deals_firm': 'has no active deals.',
      'points_reward': 'Points',
      'coffee_reward': 'Coffee',
 
      // Notifications
      'delete_all': 'Clear All',
      'no_notifications': 'No notifications.',
      'notification_deleted': 'Notification deleted.',
      'notif_welcome_title': 'Welcome! 🎉',
      'notif_welcome_msg': 'Thanks for signing up.',
      'notif_coffee_title': 'Coffee Camapign ☕',
      'notif_coffee_msg': '20% discount on all coffees at Espresso Lab!',
      'notif_points_title': 'Points Updated',
      'notif_points_msg': 'You earned 150 points from your last purchase.',
 
      // Business Detail
      'gifts': 'Gifts',
      'past_transactions': 'Past Transactions',
      'scan_for_points': 'Scan for Points',
      'gift_store': 'Gift Store',
      'your_balance': 'Your Balance',
      'stamps_progress': 'Loyalty Card Progress',
      'loading': 'Loading...',
 
      // Explore Cafes
      'search_cafe': 'Search cafes...',
      'no_cafes_found': 'No cafes found matching criteria.',
      'newly_added': 'Newly Added',
      'all_businesses': 'All Businesses',
      'no_address': 'No address info',
      'no_cafes_yet': 'No new places to explore yet.',
    },
  };

  static String getString(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? key;
  }
}
